---

- name: deploy the gitea container
  docker_container:
    name: 'gitea-app'
    image: "gitea/gitea:{{ gitea_version }}"
    volumes:
      - "gitea-data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env:
      APP_NAME: "{{ gitea_config_app_name }}"
      DB_TYPE: "{{ gitea_config_db_type }}"
      DB_HOST: "{{ gitea_config_db_host }}"
      DB_NAME: "{{ gitea_config_db_name }}"
      DB_USER: "{{ gitea_config_db_user }}"
      DB_PASSWD: "{{ gitea_config_db_passwd }}"
      DISABLE_REGISTRATION: "{{ gitea_config_disable_registration }}"
      DISABLE_SSH: "{{ gitea_config_disable_ssh }}"
      HTTP_PORT: "{{ gitea_config_http_port }}"
      LFS_START_SERVER: "{{ gitea_config_lfs_start_server }}"
      REQUIRE_SIGNIN_VIEW: "{{ gitea_config_require_signin_view }}"
      ROOT_URL: "{{ gitea_config_root_url }}"
      RUN_MODE: "{{ gitea_config_run_mode }}"
      SECRET_KEY: "{{ gitea_config_secret_key }}"
      SSH_DOMAIN: "{{ gitea_config_ssh_domain }}"
      SSH_LISTEN_PORT: "{{ gitea_config_ssh_listen_port }}"
      SSH_PORT: "{{ gitea_config_ssh_port }}"
      USER_UID: "{{ gitea_config_user_uid }}"
      USER_GID: "{{ gitea_config_user_gid }}"
    ports:
     - "{{ gitea_config_public_ssh_port }}:{{ gitea_config_ssh_port }}"
     - "3000:{{ gitea_config_http_port }}"
    restart_policy: always
    networks:
      - name: "{{ gitea_network }}"
      - name: bridge
    networks_cli_compatible: yes
    labels: |
      {
        'traefik.http.routers.gitea-app.entryPoints': 'http',
        'traefik.http.routers.gitea-app.middlewares': 'redirect',
        'traefik.http.routers.gitea-app.rule': 'Host("{{ gitea_config_root_url }}")',
        'traefik.http.routers.gitea-app-ssl.entryPoints': 'https',
        'traefik.http.routers.gitea-app-ssl.rule': 'Host("{{ gitea_config_root_url }}")',
        'traefik.http.services.gitea-app-ssl.loadbalancer.server.port': '3000',
        'traefik.http.routers.gitea-app-ssl.tls': 'true',
        'traefik.http.routers.gitea-app-ssl.tls.certResolver': 'le-ssl',
        'traefik.enable': 'true'
      }
