---

- name: deploy the gitea container
  docker_container:
    name: 'gitea-app'
    image: "gitea/gitea:{{ gitea_version }}"
    volumes:
      - "gitea-data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env: "{{ gitea_env }}"
    ports:
      - "{{ gitea_config_public_ssh_port }}:{{ gitea_config_ssh_port }}"
      - "{{ gitea_config_http_port }}:{{ gitea_config_http_port }}"
    restart_policy: always
    networks:
      - name: "{{ gitea_network }}"
      - name: bridge
    networks_cli_compatible: true
    labels: |
      {
        'traefik.http.routers.gitea-app.entryPoints': 'http',
        'traefik.http.routers.gitea-app.middlewares': 'redirect',
        'traefik.http.routers.gitea-app.rule': 'Host("{{ gitea_config_root_url }}")',
        'traefik.http.routers.gitea-app-ssl.entryPoints': 'https',
        'traefik.http.routers.gitea-app-ssl.rule': 'Host("{{ gitea_config_root_url }}")',
        'traefik.http.services.gitea-app-ssl.loadbalancer.server.port': '{{ gitea_config_http_port }}',
        'traefik.http.routers.gitea-app-ssl.tls': 'true',
        'traefik.http.routers.gitea-app-ssl.tls.certResolver': 'le-ssl',
        'traefik.enable': 'true'
      }
