---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
lint:
  name: yamllint
platforms:
  - name: gitea-docker-ubuntu-bionic
    image: ubuntu:bionic
    command: /lib/systemd/systemd
    privileged: true
    volumes:
      - /tmp/gitea-docker-ubuntu-bionic:/var/lib/docker
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
      interpreter_python: auto
    ssh_connection:
      pipelining: true
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        gitea_config_db_type: mysql
verifier:
  name: testinfra
  lint:
    name: flake8
